import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from '@/components/ui/sonner';
import Footer from '@/components/footer';
import { ThemeProvider } from '@/components/dark-mode-toogle';
import Navbar from '@/components/navbar/navbar';
import { Providers } from './provider';
import AdminMessage from './adminMessage';
import { CheckAuthenticatedUser } from './exam-countdown';
import { Suspense } from 'react';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from '@vercel/analytics/react';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider

          appearance={{
            elements: {
              // Styling primary buttons with a green color and dark mode aesthetics
              formButtonPrimary: "bg-green-500 hover:bg-green-600 text-white font-semibold py-2 px-4 rounded text-sm",
              // Styling input fields for dark mode with a focus state in green
              input: "bg-gray-700 border border-gray-600 text-white focus:ring-2 focus:ring-green-500 focus:border-transparent rounded-lg text-sm",
              // Styling labels for dark mode with a lighter text color for contrast
              label: "text-gray-300 font-semibold text-sm",

              // Additional elements can be styled here to match the dark mode theme
            },
            // Defining global variables for dark mode and green as the primary color
            variables: {
              colorPrimary: '#10b981', // Using Tailwind's green-500 as the primary color
              colorBackground: '#1f2937', // Using Tailwind's gray-800 for background color in dark mode
              colorText: '#f9fafb', // Using a light color for text in dark mode for contrast
              borderRadius: "10px",
              fontSize: "14px"
            },
          }}>

          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange

          >
            <Providers>
              <Suspense >
                <CheckAuthenticatedUser />
              </Suspense>
              <Navbar />

              <AdminMessage />
              {children}
              <Analytics />
              <SpeedInsights />
              <Footer />
              <Toaster richColors duration={7000} className='text-yellow-500' />
            </Providers>
          </ThemeProvider>
        </ClerkProvider>

      </body>
    </html>

  )
}
