import type { Metadata } from 'next'
import SideBarAndCo from './aside2'
import { Suspense } from 'react'
import SidebarSkeleton from './skeleton2'
import SubjectBadgesDrawer from './drawer'


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <div className="flex flex-row h-screen bg-white mt-8 dark:bg-gray-900">
                <Suspense fallback={<SidebarSkeleton />}>
                    <SideBarAndCo />

                </Suspense>
                <main className="flex flex-col items-center justify-center flex-1 p-4 relative md:p-8">

                    {children}
                    <div className='fixed bottom-2 right-2'>
                        <Suspense>
                            <SubjectBadgesDrawer />
                        </Suspense>
                    </div>
                </main>
            </div>

        </>



    )
}